// <auto-generated />
namespace PylonLog.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FirstTimeMigrating : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FirstTimeMigrating));
        
        string IMigrationMetadata.Id
        {
            get { return "201611042046477_FirstTimeMigrating"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
